//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.225
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Sales
{
    using System.Runtime.Serialization;
    
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="OrderInfo", Namespace="http://schemas.datacontract.org/2004/07/Sales")]
    public partial class OrderInfo : object, System.Runtime.Serialization.IExtensibleDataObject
    {
        
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        private string CustomerIdField;
        
        private int ProductNoField;
        
        private int QuantityField;
        
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData
        {
            get
            {
                return this.extensionDataField;
            }
            set
            {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string CustomerId
        {
            get
            {
                return this.CustomerIdField;
            }
            set
            {
                this.CustomerIdField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int ProductNo
        {
            get
            {
                return this.ProductNoField;
            }
            set
            {
                this.ProductNoField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int Quantity
        {
            get
            {
                return this.QuantityField;
            }
            set
            {
                this.QuantityField = value;
            }
        }
    }
}


[System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
[System.ServiceModel.ServiceContractAttribute(ConfigurationName="IOrderManager")]
public interface IOrderManager
{
    
    [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IOrderManager/PlaceOrder", ReplyAction="http://tempuri.org/IOrderManager/PlaceOrderResponse")]
    int PlaceOrder(Sales.OrderInfo info);
    
    [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IOrderManager/SellStock", ReplyAction="http://tempuri.org/IOrderManager/SellStockResponse")]
    void SellStock(int productNo, int quantity);
}

[System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
public interface IOrderManagerChannel : IOrderManager, System.ServiceModel.IClientChannel
{
}

[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
public partial class OrderManagerClient : System.ServiceModel.ClientBase<IOrderManager>, IOrderManager
{
    
    public OrderManagerClient()
    {
    }
    
    public OrderManagerClient(string endpointConfigurationName) : 
            base(endpointConfigurationName)
    {
    }
    
    public OrderManagerClient(string endpointConfigurationName, string remoteAddress) : 
            base(endpointConfigurationName, remoteAddress)
    {
    }
    
    public OrderManagerClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
            base(endpointConfigurationName, remoteAddress)
    {
    }
    
    public OrderManagerClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
            base(binding, remoteAddress)
    {
    }
    
    public int PlaceOrder(Sales.OrderInfo info)
    {
        return base.Channel.PlaceOrder(info);
    }
    
    public void SellStock(int productNo, int quantity)
    {
        base.Channel.SellStock(productNo, quantity);
    }
}
